### ISSUE TITLE
Suggestion : Write the photos to the micro SD card

### ISSUE THREAD

**Issue by onewheeltom** [MattGrayYes/Game-Boy-Camera-Fast-Wifi-Adapter#1]
Nice project! It would be a nice upgrade to also write the photos to the RPi Micro SD card as a backup

**Comment by MattGrayYes** [comment]
It does! they're saved on the Pi in /var/www/html/photos, so you can access all your previous photo downloads via the webpage, whether the Game Bo Camera cartridge is plugged in or not!
